const VALID_GAMES = new Set(['mines', 'snake']);
const SCORE_LIMITS = { mines: 100000, snake: 100000 };
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, max-age=0','x-content-type-options':'nosniff'}});}
function cleanName(value){return String(value??'').normalize('NFKC').replace(/[<>\u0000-\u001f\u007f]/g,'').replace(/\s+/g,' ').trim().slice(0,20);}
function normalizeName(value){return cleanName(value).toLocaleLowerCase('cs-CZ');}
function redisConfig(){const url=process.env.KV_REST_API_URL||process.env.UPSTASH_REDIS_REST_URL,token=process.env.KV_REST_API_TOKEN||process.env.UPSTASH_REDIS_REST_TOKEN;if(!url||!token)throw new Error('LEADERBOARD_NOT_CONFIGURED');return{url:url.replace(/\/$/,''),token};}
async function redisCommand(command){const{url,token}=redisConfig();const response=await fetch(url,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(command),cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok||data.error)throw new Error(data.error||`REDIS_HTTP_${response.status}`);return data.result;}
async function redisTransaction(commands){const{url,token}=redisConfig();const response=await fetch(`${url}/multi-exec`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(commands),cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok||data.error||!Array.isArray(data))throw new Error(data.error||`REDIS_HTTP_${response.status}`);const commandError=data.find(item=>item?.error);if(commandError)throw new Error(commandError.error);return data;}
function keys(game){return{scores:`hanz:leaderboard:${game}:scores:v1`,names:`hanz:leaderboard:${game}:names:v1`};}
async function getTop(game){const k=keys(game);const raw=await redisCommand(['ZRANGE',k.scores,0,9,'REV','WITHSCORES']);if(!Array.isArray(raw)||!raw.length)return[];const members=[],scores=[];for(let i=0;i<raw.length;i+=2){members.push(String(raw[i]??''));scores.push(Math.max(0,Math.round(Number(raw[i+1])||0)));}const displayNames=await redisCommand(['HMGET',k.names,...members]);return members.map((member,index)=>({name:cleanName(Array.isArray(displayNames)?displayNames[index]:'')||member,score:scores[index]})).filter(row=>row.name&&row.score>0).slice(0,10);}
async function handleGet(request){const url=new URL(request.url),game=url.searchParams.get('game');if(!VALID_GAMES.has(game))return json({error:'Neplatná hra.'},400);return json({game,rows:await getTop(game)});}
async function handlePost(request){const body=await request.json().catch(()=>null);if(!body||!VALID_GAMES.has(body.game))return json({error:'Neplatná hra.'},400);const name=cleanName(body.name),member=normalizeName(name),score=Math.round(Number(body.score)),maxScore=SCORE_LIMITS[body.game];if(!name||!member)return json({error:'Zadej jméno hráče.'},400);if(!Number.isFinite(score)||score<=0||score>maxScore)return json({error:'Neplatné skóre.'},400);const k=keys(body.game);const result=await redisTransaction([['ZADD',k.scores,'GT','CH',score,member],['HSET',k.names,member,name]]);const improved=Number(result?.[0]?.result||0)>0;return json({game:body.game,improved,rows:await getTop(body.game)});}
export default{async fetch(request){try{if(request.method==='GET')return await handleGet(request);if(request.method==='POST')return await handlePost(request);return json({error:'Method not allowed.'},405);}catch(error){if(String(error?.message)==='LEADERBOARD_NOT_CONFIGURED')return json({error:'Online leaderboard není připojený k databázi.'},503);console.error('Leaderboard API error:',error);return json({error:'Leaderboard je dočasně nedostupný.'},500);}}};
